### ISSUE TITLE
Joomla 4

### ISSUE THREAD

**Issue by thodorisgo** [mhajder/instant.page-joomla#1]
Hello,
any plans making this amazing plugin Joomla 4 compatible?
Kind regards

**Comment by mhajder** [comment]
Hi,
yes, I just added this to todo.

**Comment by mhajder** [comment]
@thodorisgo As I tested this plugin, it works without problems on Joomla 4. Just in case, I added Joomla 4 versions (4.[0123]) to the version requirements.

**Comment by thodorisgo** [comment]
Works like a charm thank you very much!
